### ISSUE TITLE
--clear not working on iterm2

### ISSUE THREAD

**Issue by noc7c9** [watchexec/clearscreen#1]
As it says `--clear` doesn't seem to be working at all.

watchexec 1.16.0
iterm2 3.4.6

I can also replicate on the main branch but I discovered that making the following change makes `--clear` work.
```diff
diff --git a/lib/src/run.rs b/lib/src/run.rs
index f1531c6..8c82b11 100644
--- a/lib/src/run.rs
+++ b/lib/src/run.rs
@@ -174,6 +174,7 @@ impl ExecHandler {
     fn spawn(&self, ops: &[PathOp]) -> Result<()> {
         if self.args.clear_screen {
             clearscreen::clear()?;
+            println!();
         }

         debug!("Launching command");
```

That seems super odd to me, but maybe it'll help figure out the issue.

**Comment by passcod** [comment]
Since you have watchexec building, could you test it when swapping in clearscreen from git? Otherwise I'll go test whenever I get on my mac next.

**Comment by passcod** [comment]
Actually, done. Will push out releases soon.

**Comment by noc7c9** [comment]
Thanks for the quick fix!
