### ISSUE TITLE
Compile failure: targets without InputFlags::IUTF8

### ISSUE THREAD

**Issue by fullermd** [watchexec/clearscreen#3]
`vt_well_done()` uses `InputFlags::IUTF8` unconditionally

https://github.com/watchexec/clearscreen/blob/6bd57aef6926ee98cc40b272a3421b3076bf3b1c/src/lib.rs#L723

but `nix::sys::termios` only defines it on certain targets

https://docs.rs/nix/0.22.0/src/nix/sys/termios.rs.html#604

so build fails on others (e.g., FreeBSD)

**Comment by passcod** [comment]
Thanks! Out in 1.0.6
